version: "3"

services:
  db:
    environment:
      - POSTGRES_PASSWORD=postgis
    image: mdillon/postgis:10-alpine
    ports:
      - "5432:5432"
    volumes:
      - timeline_db:/var/lib/postgresql/data

  express:
    image: node:9-alpine
    command: ["node", "build/server/index.js"]
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PGUSER=postgres
      - PGPASSWORD=postgis
      - PGDATABASE=timeline
      - PGHOST=db
    ports:
      - "3333:3000"
    user: node
    volumes:
      - ./:/app
    working_dir: /app

volumes:
  timeline_db:
